inherit_gem:
  rubocop-fjord:
    - "config/rubocop.yml"
    - "config/rails.yml"
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'
Naming/MethodParameterName:
  MinNameLength: 1
