require:
  - rubocop-rspec
inherit_gem:
  rubocop-fjord:
    - 'config/rubocop.yml'
    - 'config/rails.yml'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'
Naming/MethodParameterName:
  MinNameLength: 1
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
RSpec/ContextWording:
  AllowedPatterns:
    - とき$
    - 場合$
RSpec/MultipleMemoizedHelpers:
  Enabled: false
